[package]
name = "rigorstarter-rust-tauri-webgpu"
version = "0.1.0"
edition = "2024"
default-run = "rigorstarter-rust-tauri-webgpu"

[dependencies]
winit = "0.30"
wgpu = "29"
pollster = "0.4"
env_logger = "0.11"
rand = "0.8"
bytemuck = "1.25"
glyphon = "0.11"
fontdb = "0.23"
cosmic-text = "0.18"

[[bin]]
name = "rigorstarter-rust-tauri-webgpu"
path = "src/main.rs"
